### ISSUE TITLE
Robot_2D_localization example

### ISSUE THREAD

**Issue by BenedictChannn** [symforce-org/symforce#328] opened 2023-05-19 09:27 UTC
Somehow I keep getting a runtime error when trying to run the robot 2D localization example. Does anyone know what I did wrong/ can be done to solve the error?

**Comment by aaron-skydio** [comment] 2023-06-01 21:08
Closing, assuming this is a duplicate of #308 - if you're hitting a separate error feel free to reopen and post the specific error

**Closed by aaron-skydio** 2023-06-01 21:08 UTC
